[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "py-inventory-v2-a2a"
version = "0.1.0"
description = "A a2a agent in charge of inventory affairs."
dependencies = [
    "pydantic",
    "fastapi",
    "uvicorn",
    "gunicorn",
    "numpy",
]